env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: proji-darwin-amd64
    ldflags: -s -w -X github.com/proji/proji.Version={{.Version}} -X github.com/proji/proji.BuildDate={{.Date}} -X github.com/proji/proji.CommitHash={{ .ShortCommit }}
    binary: proji
    env:
      - CGO_ENABLED=1
      - CC=x86_64-apple-darwin14-cc
    main: ./cmd/proji/main.go
    goos:
      - darwin
    goarch:
      - amd64
  - id: proji-linux-amd64
    ldflags: -s -w -X github.com/proji/proji.Version={{.Version}} -X github.com/proji/proji.BuildDate={{.Date}} -X github.com/proji/proji.CommitHash={{ .ShortCommit }}
    binary: proji
    env:
      - CGO_ENABLED=1
    main: ./cmd/proji/main.go
    goos:
      - linux
    goarch:
      - amd64
  - id: proji-windows-amd64
    ldflags: -s -w -X github.com/proji/proji.Version={{.Version}} -X github.com/proji/proji.BuildDate={{.Date}} -X github.com/proji/proji.CommitHash={{ .ShortCommit }}
    binary: proji
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    main: ./cmd/proji/main.go
    goos:
      - windows
    goarch:
      - amd64
  - id: proji-linux-arm64
    ldflags: -s -w -X github.com/proji/proji.Version={{.Version}} -X github.com/proji/proji.BuildDate={{.Date}} -X github.com/proji/proji.CommitHash={{ .ShortCommit }}
    binary: proji
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    main: ./cmd/proji/main.go
    goos:
      - linux
    goarm:
      - 6
      - 7
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
brews:
  - github:
      owner: nikoksr
      name: homebrew-taps
    commit_author:
      name: Niko Köser
      email: koeserniko@gmail.com
    folder: Formula
    homepage: "https://github.com/nikoksr/proji"
    install: |
      bin.install "proji"
    description: "A powerful cross-platform CLI project templating tool."
scoop:
  bucket:
    owner: nikoksr
    name: scoop-bucket
  commit_author:
    name: Niko Köser
    email: koeserniko@gmail.com
  homepage: "https://github.com/nikoksr/proji"
  description: "A powerful cross-platform CLI project templating tool."
  license: MIT
nfpms:
  -
    id: proji-linux-amd64 
    package_name: proji
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      linux: Linux
    homepage: https://github.com/nikoksr/proji
    maintainer: Niko Köser <koeserniko@gmail.com>
    description: A powerful cross-platform CLI project templating tool.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
snapcrafts: 
  -
    id: proji-linux-amd64 
    builds:
      - proji-linux-amd64
    name: proji
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      linux: Linux
    publish: true
    description: |
      **Key Features**

      *   Creates project directories of any size **in seconds**
      *   Project templates are based on **individual config files**
      *   Structures of **GitHub/GitLab repos can be imported** as templates
      *   Structures of **directories can be imported** as templates
      *   Infinitely extendable through integration of **custom shell scripts**
      *   Supports **custom template files**
      *   **Shareable** project configs
      *   Projects are **not bound to any language or framework**
      *   Boosts your **productivity** and simplifies your **workflow**
      *   Works on **Windows**, **macOS** and **Linux**
    summary: A powerful cross-platform CLI project templating tool.
    confinement: strict
    license: MIT
    base: bare
