name = "c-lang"
label = "c"
description = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et."

[[template]]
  is_file = true
  path = "CMakeLists-c.txt"
  destination = "CMakeLists.txt"
  description = ""

[[template]]
  is_file = true
  path = "README.md"
  destination = "README.md"
  description = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et."

[[template]]
  is_file = true
  path = "main.c"
  destination = "src/main.c"
  description = ""

[[template]]
  is_file = false
  path = "vscode-cpp"
  destination = ".vscode"
  description = ""

[[template]]
  is_file = false
  path = ""
  destination = "build/debug/bin"
  description = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et."

[[template]]
  is_file = false
  path = ""
  destination = "build/release/bin"
  description = ""

[[template]]
  is_file = false
  path = ""
  destination = "include"
  description = ""

[[template]]
  is_file = false
  path = ""
  destination = "src"
  description = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et."

[[template]]
  is_file = false
  path = ""
  destination = "test"
  description = ""

[[plugin]]
  path = "init_something_else.sh"
  exec_number = -1
  description = "Lorem ipsu"

[[plugin]]
  path = "init_git.sh"
  exec_number = 1
  description = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata"

[[plugin]]
  path = "init_something.sh"
  exec_number = 2
  description = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore"
