version: 2

jobs:
  build:
    docker:
      - image: cimg/go:1.14.4

    working_directory: /home/circleci/go/src/github.com/nikoksr/proji

    steps:
      - checkout

      - run:
          name: Install sqlite
          command: sudo apt install -y sqlite3 || true

      - run:
          name: Install proji
          command: go install ./cmd/proji

      - run:
          name: Initialize proji
          command: proji init

      - run:
          name: Run go vet
          command: go vet ./...

      - run:
          name: Run go test
          command: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...

      - run:
          name: Upload results to codecov
          command: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: test-results-proji

      - store_artifacts:
          path: test-results-proji
          destination: trp

  release:
    docker:
      - image: mailchain/goreleaser-xcgo:v0.9.0
      - image: cibuilds/snapcraft:stable

    working_directory: /go/src/github.com/nikoksr/proji

    steps:
      - checkout

      - run:
          name: Login to snap store
          command: |
            echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > snapcraft.login
            snapcraft login --with snapcraft.login

      - run:
          name: Deploy releases
          command: goreleaser --rm-dist

workflows:
  version: 2
  wf-build:
    jobs:
      - build
  wf-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
