version: 2

jobs:
  build:
    working_directory: ~/create_project
    docker:
      - image: circleci/python:3.7.4

    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run: sudo apt install -y sqlite3 || true
      - run: mkdir -p ~/.config/create_project/db
      - run: sqlite3 ~/.config/create_project/db/cp.sqlite3 < scripts/create_basic_db.sql
      - run: cp -r templates ~/.config/create_project/
      - run: pip install --user -r requirements.txt

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.local/lib/python3.7/site-packages"

      - run:
          command: |
            pytest -v

      - store_test_results:
          path: test-results-python-3.7.4
      - store_artifacts:
          path: test-results-python-3.7.4
          destination: trp374
