version: 2

jobs:
  build:
    working_directory: ~/create_project
    docker:
      - image: circleci/python:3.7.4
      - image: circleci/sqlite3:3.29.0

    steps:
      - checkout
      - restore_cache:
        key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run: mkdir -p ~/.config/create_project/db
      - run: sqlite3 ~/.config/create_project/db/cp.sqlite3 < scripts/create_basic_db.sql
      - run: cp -r templates ~/.config/create_project/
      - run:
        command: |
          virtualenv .env
          source .env/bin/activate
          pip install -r requirements.txt

      - save_cache:
        key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
        paths:
          - ".env"

      - run:
        command: |
          pytest -v

      - store_test_results:
          path: test-results-python-3.7.4
      - store_artifacts:
          path: test-results-python-3.7.4
          destination: trp374
