version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/nikoksr/proji
    steps:
      - checkout

      - run:
          name: Setup config directory
          command: |
            mkdir -p ~/.config/proji/db
            mkdir -p ~/.config/proji/examples
            mkdir -p ~/.config/proji/scripts
            mkdir -p ~/.config/proji/templates
            cp configs/example-config.toml ~/.config/proji/config.toml
            cp configs/example-class-export.toml ~/.config/proji/examples/proji-class.toml
            echo "# This is a template readme" > ~/.config/proji/templates/README.md

      - run:
          name: Install sqlite
          command: sudo apt install -y sqlite3 || true

      - run:
          name: Install go dependencies
          command: go get -v -t -d ./...

      - run:
          name: Run go vet
          command: go vet ./...

      - run:
          name: Run go test
          command: go test -v ./...

      - store_test_results:
          path: test-results-proji

      - store_artifacts:
          path: test-results-proji
          destination: trp
