version: 2

jobs:
  build:
    docker:
      - image: cimg/go:1.14.4

    working_directory: /home/circleci/go/src/github.com/nikoksr/proji

    steps:
      - checkout

      - run:
          name: Install sqlite
          command: sudo apt install -y sqlite3 || true

      - run:
          name: Install proji
          command: go install ./cmd/proji

      - run:
          name: Initialize proji
          command: proji init

      - run:
          name: Run go vet
          command: go vet ./...

      - run:
          name: Run go test
          command: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...

      - run:
          name: Upload results to codecov
          command: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: test-results-proji

      - store_artifacts:
          path: test-results-proji
          destination: trp

  release:
    docker:
      - image: mailchain/goreleaser-xcgo:v0.9.0

    working_directory: /go/src/github.com/nikoksr/proji

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install -y squashfs-tools && rm -rf /var/lib/apt/lists/*

      - run:
          name: Install the core snap, a dependency of the snapcraft snap
          command: |
            curl -L $(curl -H "X-Ubuntu-Series: 16" "https://api.snapcraft.io/api/v1/snaps/details/core" | jq ".download_url" -r) --output core.snap
            mkdir -p /snap/core
            unsquashfs -d /snap/core/current core.snap
            rm -f core.snap

      - run:
          name: Install the core18 snap
          command: |
            curl -L $(curl -H "X-Ubuntu-Series: 16" "https://api.snapcraft.io/api/v1/snaps/details/core18" | jq ".download_url" -r) --output core18.snap
            mkdir -p /snap/core18
            unsquashfs -d /snap/core18/current core18.snap
            rm -f core18.snap

      - run:
          name: Install the snapcraft snap
          command: |
            curl -L $(curl -H "X-Ubuntu-Series: 16" "https://api.snapcraft.io/api/v1/snaps/details/snapcraft?channel=stable" | jq ".download_url" -r) --output snapcraft.snap
            mkdir -p /snap/snapcraft
            unsquashfs -d /snap/snapcraft/current snapcraft.snap
            rm -f snapcraft.snap

      - run:
          name: Add snap to path
          command: echo "export PATH=/snap/bin:/snap/snapcraft/current/bin:$PATH" >> $BASH_ENV

      - run:
          name: Login to snap store
          command: |
            echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > snapcraft.login
            snapcraft login --with snapcraft.login

      - run:
          name: Deploy releases
          command: goreleaser --rm-dist

workflows:
  version: 2
  wf-build:
    jobs:
      - build
  wf-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
