# Proji class template file

# The actual class name.
# Must be unique and expressive.
# name = "myTestClass" <- Good
# name = "t1"          <- Bad, too short and not expressive
name = "example"

# A short class label. The label must be unique and
# should ideally be an abbreviation of the class name or something similar.
# Later on the label will be used to quickly create your projects.
# e.g.: proji create YOUR-LABEL my-new-project1 my-new-project2
# label = "mtc"                <- Good
# label = "myTestClassLabel"   <- Bad - too long
# label = "ilt"                <- Bad - unrelated to class name
label = "exp"

[folders]
# Folders to create in or copy to the project folder.
# Target is a relative path inside the project folder.
# Template is a relative path to a folder in the configs template folder.
# (~/.config/proji/templates/)
# If you don't want to create a folder by copying a template, just leave
# out the template field and only specify the target. This will create an
# empty folder.

# Synatx: "TARGET" = "TEMPLATE"
# "myNewFolder/" = ""           <- no template, just create the file
# "foo/bar/" = "templateName"   <- copy template to target location
"exampleFolder/" = ""
"foo/bar/" = ""

[files]
# Files to create in or copy to the project folder.
# See [folders] for instructions.

# "text/myFile.txt" = ""
# "myTargetFile.txt" = "templateFile.txt"
"README.md" = "README.md"
"exampleFolder/test.txt" = ""

[scripts]
# Scripts you want to execute after the project structure was created.
# First value should be a script that lies inside the scripts folder (~/.config/proji/scripts/).
# The second value is of type boolean and should be true or false
# respectively if the script needs to be executed as root or not.

# Syntax: "SCRIPTNAME" = RUN_AS_SUDO
# "myScript.sh" = false    <- run my script as regular user
# "mySudoScript.sh" = true <- run my script as root
